[package]
name = "game-server"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tungstenite = "0.17.3"

tokio = { version = "1", features = ["full"] }
warp = "0.3"
bytes = "1.3.0"
chrono = "0.4.23"