[package]
name = "game-model"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nanoserde = "0.2.1"
colored = "3.1.1"
indexmap = "2.13.0"
